/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.cidenet.hulkstore.factory;

import java.sql.Connection;
import com.cidenet.hulkstore.dao.*;
import com.cidenet.hulkstore.jdbc.*;

public class StoreDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return StoreDao
	 */
	public static StoreDao create()
	{
		return new StoreDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return StoreDao
	 */
	public static StoreDao create(Connection conn)
	{
		return new StoreDaoImpl( conn );
	}

}
