/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.cidenet.hulkstore.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.cidenet.hulkstore.dao.DocumentDao;
import com.cidenet.hulkstore.dto.Document;
import com.cidenet.hulkstore.exceptions.DocumentDaoException;
import com.cidenet.hulkstore.factory.DocumentDaoFactory;

public class DocumentDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereDocumentIdEquals(0);
		// findWhereDocumentDescriptionEquals("");
		// findWhereStateEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			DocumentDao _dao = getDocumentDao();
			Document _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDocumentIdEquals'
	 * 
	 * @param documentId
	 */
	public static void findWhereDocumentIdEquals(int documentId)
	{
		try {
			DocumentDao _dao = getDocumentDao();
			Document _result[] = _dao.findWhereDocumentIdEquals(documentId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDocumentDescriptionEquals'
	 * 
	 * @param documentDescription
	 */
	public static void findWhereDocumentDescriptionEquals(String documentDescription)
	{
		try {
			DocumentDao _dao = getDocumentDao();
			Document _result[] = _dao.findWhereDocumentDescriptionEquals(documentDescription);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStateEquals'
	 * 
	 * @param state
	 */
	public static void findWhereStateEquals(short state)
	{
		try {
			DocumentDao _dao = getDocumentDao();
			Document _result[] = _dao.findWhereStateEquals(state);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getDocumentDao'
	 * 
	 * @return DocumentDao
	 */
	public static DocumentDao getDocumentDao()
	{
		return DocumentDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Document dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getDocumentId() );
		buf.append( ", " );
		buf.append( dto.getDocumentDescription() );
		buf.append( ", " );
		buf.append( dto.getState() );
		System.out.println( buf.toString() );
	}

}
