/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.cidenet.hulkstore.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.cidenet.hulkstore.dao.ProductDao;
import com.cidenet.hulkstore.dto.Product;
import com.cidenet.hulkstore.exceptions.ProductDaoException;
import com.cidenet.hulkstore.factory.ProductDaoFactory;

public class ProductDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereProductIdEquals(0);
		// findWhereProductNameEquals("");
		// findWhereUnityIdEquals(0);
		// findWhereStateEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ProductDao _dao = getProductDao();
			Product _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductIdEquals'
	 * 
	 * @param productId
	 */
	public static void findWhereProductIdEquals(int productId)
	{
		try {
			ProductDao _dao = getProductDao();
			Product _result[] = _dao.findWhereProductIdEquals(productId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProductNameEquals'
	 * 
	 * @param productName
	 */
	public static void findWhereProductNameEquals(String productName)
	{
		try {
			ProductDao _dao = getProductDao();
			Product _result[] = _dao.findWhereProductNameEquals(productName);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUnityIdEquals'
	 * 
	 * @param unityId
	 */
	public static void findWhereUnityIdEquals(int unityId)
	{
		try {
			ProductDao _dao = getProductDao();
			Product _result[] = _dao.findWhereUnityIdEquals(unityId);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereStateEquals'
	 * 
	 * @param state
	 */
	public static void findWhereStateEquals(short state)
	{
		try {
			ProductDao _dao = getProductDao();
			Product _result[] = _dao.findWhereStateEquals(state);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getProductDao'
	 * 
	 * @return ProductDao
	 */
	public static ProductDao getProductDao()
	{
		return ProductDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Product dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getProductId() );
		buf.append( ", " );
		buf.append( dto.getProductName() );
		buf.append( ", " );
		buf.append( dto.getUnityId() );
		buf.append( ", " );
		buf.append( dto.getState() );
		System.out.println( buf.toString() );
	}

}
