/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.cidenet.hulkstore.dao;

import com.cidenet.hulkstore.dto.*;
import com.cidenet.hulkstore.exceptions.*;

public interface KardexDao
{
	/** 
	 * Inserts a new row in the kardex table.
	 */
	public KardexPk insert(Kardex dto) throws KardexDaoException;

	/** 
	 * Updates a single row in the kardex table.
	 */
	public void update(KardexPk pk, Kardex dto) throws KardexDaoException;

	/** 
	 * Deletes a single row in the kardex table.
	 */
	public void delete(KardexPk pk) throws KardexDaoException;

	/** 
	 * Returns the rows from the kardex table that matches the specified primary-key value.
	 */
	public Kardex findByPrimaryKey(KardexPk pk) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'productId = :productId AND storeId = :storeId'.
	 */
	public Kardex findByPrimaryKey(int productId, int storeId) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria ''.
	 */
	public Kardex[] findAll() throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'productId = :productId'.
	 */
	public Kardex[] findByProduct(int productId) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'storeId = :storeId'.
	 */
	public Kardex[] findByStore(int storeId) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'productId = :productId'.
	 */
	public Kardex[] findWhereProductIdEquals(int productId) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'storeId = :storeId'.
	 */
	public Kardex[] findWhereStoreIdEquals(int storeId) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'quantity = :quantity'.
	 */
	public Kardex[] findWhereQuantityEquals(double quantity) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'unityValue = :unityValue'.
	 */
	public Kardex[] findWhereUnityValueEquals(double unityValue) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'totalValue = :totalValue'.
	 */
	public Kardex[] findWhereTotalValueEquals(double totalValue) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the criteria 'state = :state'.
	 */
	public Kardex[] findWhereStateEquals(short state) throws KardexDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the kardex table that match the specified arbitrary SQL statement
	 */
	public Kardex[] findByDynamicSelect(String sql, Object[] sqlParams) throws KardexDaoException;

	/** 
	 * Returns all rows from the kardex table that match the specified arbitrary SQL statement
	 */
	public Kardex[] findByDynamicWhere(String sql, Object[] sqlParams) throws KardexDaoException;

}
