/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.cidenet.hulkstore.dao;

import com.cidenet.hulkstore.dto.*;
import com.cidenet.hulkstore.exceptions.*;

public interface UsersDao
{
	/** 
	 * Inserts a new row in the users table.
	 */
	public UsersPk insert(Users dto) throws UsersDaoException;

	/** 
	 * Updates a single row in the users table.
	 */
	public void update(UsersPk pk, Users dto) throws UsersDaoException;

	/** 
	 * Deletes a single row in the users table.
	 */
	public void delete(UsersPk pk) throws UsersDaoException;

	/** 
	 * Returns the rows from the users table that matches the specified primary-key value.
	 */
	public Users findByPrimaryKey(UsersPk pk) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'userId = :userId'.
	 */
	public Users findByPrimaryKey(int userId) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria ''.
	 */
	public Users[] findAll() throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'userId = :userId'.
	 */
	public Users[] findWhereUserIdEquals(int userId) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'userName = :userName'.
	 */
	public Users[] findWhereUserNameEquals(String userName) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'userPass = :userPass'.
	 */
	public Users[] findWhereUserPassEquals(String userPass) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'identification = :identification'.
	 */
	public Users[] findWhereIdentificationEquals(String identification) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'realName = :realName'.
	 */
	public Users[] findWhereRealNameEquals(String realName) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'surname = :surname'.
	 */
	public Users[] findWhereSurnameEquals(String surname) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'userProfile = :userProfile'.
	 */
	public Users[] findWhereUserProfileEquals(short userProfile) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the criteria 'state = :state'.
	 */
	public Users[] findWhereStateEquals(short state) throws UsersDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the users table that match the specified arbitrary SQL statement
	 */
	public Users[] findByDynamicSelect(String sql, Object[] sqlParams) throws UsersDaoException;

	/** 
	 * Returns all rows from the users table that match the specified arbitrary SQL statement
	 */
	public Users[] findByDynamicWhere(String sql, Object[] sqlParams) throws UsersDaoException;

}
